# Version for the build. We make it clear that it's
# Appveyor as this isn't a version we expect to make
# it elsewhere...
version: 1.0.{build}-appveyor

image: Visual Studio 2017

branches:
  only:
    - master

init:
  - git config --global core.autocrlf true
  
# TODO(talarico): Temporary work around for https://appveyor.statuspage.io/incidents/m2vdvw39kdk8
hosts:
  api.nuget.org: 93.184.221.200

environment:
  COVERALLS_REPO_TOKEN:
    secure: 0F41/ccYgoYS098AEpBDGjBToFMvBsrjGLRzOW+ViyY4QrIzVIUmMlKiuNXDDeAs

# Install the pre-requisites for the build.
install:
  # Make sure curl is available
  - set PATH=C:\Program Files\Git\mingw64\bin;%PATH%
  # Download and unpack docfx
  - mkdir docfx
  - cd docfx
  - curl -SL https://github.com/dotnet/docfx/releases/download/v2.20/docfx.zip -o docfx.zip
  - unzip docfx.zip
  - cd ..
  # add dotnet and docfx to PATH
  - ps: $env:Path = "$env:DOTNET_INSTALL_DIR;$pwd\docfx;$env:Path"

# Perform the build.
build_script:
  - dotnet --info
  - echo "Regenerating projects: if this fails, run generateprojects.sh and commit changes"
  - echo "Current Time is %time%"
  - generateprojects.sh && git diff --exit-code
  - echo "Current Time is %time%"
  - bash build.sh
  - echo "Current Time is %time%"
  - cd docs
  - bash builddocs.sh
  - echo "Current Time is %time%"

# TODO: Reinstate these...
#  - bash runcoverage.sh
#  - bash coveralls.sh

# The tests are run as part of the build.
test: off
