// Copyright 2017 Google Inc. All Rights Reserved.
// 
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
// 
//     http://www.apache.org/licenses/LICENSE-2.0
// 
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

using System;
using System.Threading;
using System.Threading.Tasks;
using Google.Api.Gax;
using Google.Apis.Bigquery.v2.Data;

namespace Google.Cloud.BigQuery.V2
{
	//THIS CODE TO BE AUTOGENERATED
    // EXAMPLE OF NON-COMMAND GENERATED WRAPPERS

    /// <summary>
    /// </summary>
    public sealed partial class BigQueryConnection
    {
        /// <summary>
        /// </summary>
        public PagedEnumerable<JobList, BigQueryJob> ListJobs(ListJobsOptions options = null)
        {
            AssertOpen();
            return BigQueryClient.ListJobs(
                BigQueryClient.GetProjectReference(_connectionStringBuilder.Project),
                options);
        }
    }

}
