// Copyright 2017 Google Inc. All Rights Reserved.
// 
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
// 
//     http://www.apache.org/licenses/LICENSE-2.0
// 
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

// ReSharper disable UnusedParameter.Local
// ReSharper disable EmptyNamespace

using System;
using System.Data.Common;

namespace Google.Cloud.Spanner
{
#if NET45 || NET451

//    /// <summary>
//    /// </summary>
//    public sealed class SpannerCommandBuilder
//    {
//        private SpannerDataAdapter _adapter;
//
//        /// <summary>
//        /// 
//        /// </summary>
//        public string UpdateTable { get; set; }
//
//        /// <summary>
//        /// 
//        /// </summary>
//        public SpannerDataAdapter Adapter
//        {
//            get { return _adapter; }
//            set
//            {
//                DbCommandBuilder
//                _adapter = value;
//
//                if (_adapter.UpdateCommand == null && _adapter.SelectCommand != null)
//                {
//                    if (_adapter.SelectCommand.ParsedParameterCollection.Count > 0)
//                    {
//                        SetUpdateCommand(_adapter.SelectCommand.ParsedParameterCollection);
//                    }
//                    else
//                    {
//                        _adapter.SelectCommand.AutoGeneratedParametersReady +=
//                            (sender, collection) => SetUpdateCommand(collection);
//                    }
//                }
//            }
//        }
//
//        /// <summary>
//        /// 
//        /// </summary>
//        public SpannerCommandBuilder()
//        {
//
//        }
//
//        /// <summary>
//        /// 
//        /// </summary>
//        /// <param name="adapter"></param>
//        /// <param name="updateTable"></param>
//        public SpannerCommandBuilder(DbDataAdapter adapter, string updateTable)
//        {
//            Adapter = (SpannerDataAdapter)adapter;
//            UpdateTable = updateTable;
//
//        }
//
//        private void SetUpdateCommand(SpannerParameterCollection parsedParameterCollection)
//        {
//            if (_adapter.UpdateCommand == null)
//            {
//                _adapter.UpdateCommand = new SpannerCommand(SpannerCommandTextBuilder.NewUpdateOperation(UpdateTable), _adapter.SelectCommand.SpannerConnection, null, parsedParameterCollection);
//            }
//        }
//    }

#endif
}